# Лабораторная работа №1
Группа 45/1
---

**Импорт библиотек**

In [1]:
import numpy as np
from collections import Counter

**Задание 1.**
Создать вектор (одномерный массив) размера 10, заполненныйединицами.

In [2]:
# Создаем вектор размером 10, заполненный единицами
vector = np.ones(10)

print(vector)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Задание 2.**
Создать вектор (одномерный массив) со значениями от 10 до 49

In [3]:
# Создаем вектор со значениями от 10 до 49
vector = np.arange(10, 50)

print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Задание 3.**
Создать вектор (одномерный массив) размера 10. Заполнить его случайными значениями. Найти индексы ненулевых элементов

In [4]:
# Создаем вектор размером 10 с случайными значениями от 0 до 1
vector = np.random.rand(10)

# Находим индексы ненулевых элементов
non_zero_indices = np.nonzero(vector)

print("Вектор с случайными значениями:")
print(vector)
print("Индексы ненулевых элементов:")
print(non_zero_indices)

Вектор с случайными значениями:
[0.82426744 0.366953   0.89777409 0.87622024 0.56186602 0.321751
 0.73628981 0.95846936 0.26617654 0.7431967 ]
Индексы ненулевых элементов:
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)


**Задание 4.**
Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [5]:
# Создаем матрицу 3x3 с значениями от 0 до 8
matrix = np.arange(9).reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Задание 5.**
Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [6]:
# Создаем базовую матрицу 2x2 для шахматной доски
base_matrix = np.array([[0, 1], [1, 0]])

# Используем функцию tile, чтобы создать 8x8 матрицу, повторяя базовую матрицу
chessboard = np.tile(base_matrix, (4, 4))

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Задание 6.**
Создать вектор (одномерный массив) размера 10. Заполнить его случайными значениями. Заменить минимальный элемент на ноль

In [7]:
# Создаем вектор размером 10 с случайными значениями
vector = np.random.rand(10)

# Находим индекс минимального элемента в векторе
min_index = np.argmin(vector)

# Заменяем минимальный элемент на ноль
vector[min_index] = 0

print("Вектор с случайными значениями и заменой минимального элемента на ноль:")
print(vector)

Вектор с случайными значениями и заменой минимального элемента на ноль:
[0.90791093 0.58189294 0.73630966 0.81856123 0.         0.6190912
 0.98484797 0.8646304  0.17127597 0.97472307]


**Задание 7.**
Создать вектор (одномерный массив) размера 100. Заполнить его случайными значениями. Найти наиболее частое значение в массиве

In [8]:
# Создаем вектор размером 100 с случайными значениями от 0 до 9
vector = np.random.randint(0, 10, 100)

# Используем Counter для подсчета частоты каждого значения
value_counts = Counter(vector)

# Находим наиболее частое значение
most_common_value = value_counts.most_common(1)[0][0]

print("Вектор с случайными значениями:")
print(vector)
print(f"Наиболее частое значение: {most_common_value}")

Вектор с случайными значениями:
[6 5 6 4 0 9 7 5 0 4 8 7 3 1 3 2 1 7 0 8 5 2 8 7 2 2 5 4 3 4 3 7 3 1 0 6 5
 0 9 4 9 7 2 6 5 6 7 4 3 9 9 6 4 4 1 9 4 0 1 9 6 5 4 8 8 2 9 1 6 2 4 6 7 0
 7 6 5 4 2 9 1 3 7 7 6 6 9 6 1 3 0 4 1 8 9 0 0 2 6 6]
Наиболее частое значение: 6


**Задание 8.**
Создать матрицу. Отнять среднее из каждой строки в матрице

In [9]:
# Создаем матрицу 3x3 (в данном случае) для примера
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Вычисляем среднее значение каждой строки
row_means = np.mean(matrix, axis=1)

# Отнимаем средние значения из каждой строки
normalized_matrix = matrix - row_means.reshape(-1, 1)

print("Исходная матрица:")
print(matrix)

print("Матрица с отнятыми средними значениями из каждой строки:")
print(normalized_matrix)

Исходная матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Матрица с отнятыми средними значениями из каждой строки:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


**Задание 9.**
Создать матрицу. Поменять две строки в матрице

In [10]:
# Создаем матрицу 3x3 (в данном случае) для примера
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Выводим исходную матрицу
print("Исходная матрица:")
print(matrix)

# Меняем местами строки 1 и 2 (в Python индексация начинается с 0)
matrix[[1, 2]] = matrix[[2, 1]]

print("Матрица после обмена строк 1 и 2:")
print(matrix)

Исходная матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Матрица после обмена строк 1 и 2:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


**Задание 10.**
Создать вектор (одномерный массив) размера 10. Заполнить его случайными значениями. Найти n наибольших значений в векторе

In [11]:
# Создаем вектор размером 10 с случайными значениями от 0 до 1
vector = np.random.rand(10)

# Указываем количество наибольших значений, которые мы хотим найти (в данном случае 3)
n = 3

# Находим n наибольших значений в векторе
top_n_values = np.partition(vector, -n)[-n:]

# Сортируем полученные значения по убыванию, если это необходимо
top_n_values = np.sort(top_n_values)[::-1]

print("Вектор с случайными значениями:")
print(vector)
print(f"{n} наибольших значений в векторе:")
print(top_n_values)

Вектор с случайными значениями:
[0.13758908 0.36769235 0.45296892 0.82025058 0.19980338 0.62583927
 0.09854688 0.36759691 0.96476097 0.14564347]
3 наибольших значений в векторе:
[0.96476097 0.82025058 0.62583927]


**Задание 11.**
Создать 5x5 матрицу со значениями в строках от 1 до 5.

In [12]:
# Создаем матрицу 5x5, где каждая строка содержит значения от 1 до 5
matrix = np.array([np.arange(1, 6)] * 5)

print(matrix)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


**Задание 12.**
Создать две матрицы 4x4 и 4x4. Найти их произведение. Найти диагональные элементы произведения матриц

In [13]:
# Создаем первую матрицу 4x4 (пример)
matrix1 = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

# Создаем вторую матрицу 4x4 (пример)
matrix2 = np.array([[17, 18, 19, 20],
                    [21, 22, 23, 24],
                    [25, 26, 27, 28],
                    [29, 30, 31, 32]])

# Находим произведение матриц
product_matrix = np.dot(matrix1, matrix2)

# Находим диагональные элементы произведения матриц
diagonal_elements = np.diagonal(product_matrix)

print("Первая матрица:")
print(matrix1)

print("Вторая матрица:")
print(matrix2)

print("Произведение матриц:")
print(product_matrix)

print("Диагональные элементы произведения:")
print(diagonal_elements)

Первая матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Вторая матрица:
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
Произведение матриц:
[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]
Диагональные элементы произведения:
[ 250  644 1070 1528]
